### PR TITLE
Feature/documentation updates

### PR DESCRIPTION
**Pull request by viklund**
### Describe the pull request:

- [x] Documentation change

### Pull request long description:
Updated documentation to be a little bit clearer.

### CODE REVIEW

**Review by jbygdell — COMMENTED** [review]
How do we then tell the user that the path is different if they have cloned the git repo compared to if they have downloaded the chart via helm?

**Comment by jonandernovella** [comment]
@viklund Jocke is referring to what I told you before. Unless we enforce downloading the chart via Helm it won't work.

**Comment by viklund** [comment]
> How do we then tell the user that the path is different if they have cloned the git repo compared to if they have downloaded the chart via helm?

Hmm, maybe we should just do a `[ega-charts/]` prefix and/or write a sentence about it.

**Review by jonandernovella — APPROVED** [review]

**Review by blankdots — APPROVED** [review]

**Pull request merged**
