### PR TITLE
FileStorage backend for Data Archive.

### LINKED ISSUE #44: FileStorage backend for Archive fails with permission denied
### Expected Behavior
`ingest` and `verify` should be able to use a co-located archive on a `hostPath`

### Current Behavior
When setting in `values.yaml` the following `config` parameters:
```
data_storage_type: "FileStorage"
data_storage_location: "/ega/archive" # path to data archive volume
data_storage_mode: 2750
```
`ingest` service fails with:
```
[lega.ingest][ INFO ] (L82) [FileStorage] Moving the rest of 2019-07-18_04-37-15.c4ga to /000/000/000/000/000/000/01
[lega.utils.db][ERROR ] (L246) Exception: <class 'PermissionError'> in /usr/local/lib/python3.6/site-packages/lega/utils/db.py on line: 277
[lega.utils.db][ERROR ] (L249) PermissionError(13, 'Permission denied') (from user: False)
[lega.utils.db][DEBUG ] (L131) Setting error for 1: [Errno 13] Permission denied: '/ega/archive/lega' | Cause: None
```

The `ingest` service fails to access the volume due to group permissions.

### Possible Solution
1. Add `volumeMounts` to both `ingest` and `verify` based on `.Values.config.data_storage_type` equal to `FileStorage`.
2. Add `volume` to both `ingest` and `verify` based on `.Values.config.data_storage_type` equal to `FileStorage` also make it co-located aware.
3. The first two steps might not be enough as even though the file might be `ingest`ed it still needs to share directory with `verify` service
4. Setting node affinity for `verify` to be on the same node as `ingest`. Might need the same for `res` service.

### Steps to Reproduce

1. Set in `values.yaml` the values as pointed in **Current Behavior** above
2. Run e2e tester

### Context (Environment)
Run helm charts with `FileStorage` as archive.

### PR DESCRIPTION
**Pull request by jbygdell**
### Describe the pull request:

- [X] Bug fix
- [ ] Functional change
- [X] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

This adds posix based storage backend for Data Archive, available options are NFS, local-PV and flex-volume.
Storage backend is defined in ingest and used by res and verify.
### Changes made:

1) Add option to co-locate verify and res with ingest.
2) Add FileStorage backend to ingest, verify  and res
3) Replaces spring profile `LocalEGA` with `default` for RES when FileStorage backend is in use
3) Prepare e2e-tester for a FileStorage backend

### Related issues:

Fixes #44 
### Additional information:

This is wholly untested since the e2e-tester is not designed to work with a non S3 backend.

### CODE REVIEW

**Review by blankdots — APPROVED** [review]
we will need the new code from e2e tester to make a test on our CI

**Review by viklund — CHANGES_REQUESTED** [review]
There are a number of places where the conditional is

```if and .Values.persistence.enabled .Values.podSecurityPolicy.create```

And then followed by a plain `else` later on. I'm not versed enough in this part of the setup to understand if this is a potential issue or not. Is it always fine to go into the `else` branch if only one or the other is true? I need some more information here.

**Comment by jbygdell** [comment]
> There are a number of places where the conditional is
>
>if and .Values.persistence.enabled .Values.podSecurityPolicy.create
>
>And then followed by a plain else later on. I'm not versed enough in this part of the setup to >understand if this is a potential issue or not. Is it always fine to go into the else branch if only one or >the other is true? I need some more information here.

If you look in the `else` block you see that it is `hostPath` that is being specified.
We only allow `hostPath` when we don't use pod security policies and `hostPath` is not a persistent volume since the pod might be scheduled on another node next time it starts.

**Review by viklund — APPROVED** [review]

**Comment by blankdots** [comment]
@jbygdell should we have made a version bump for this ? or it can wait till https://github.com/NBISweden/LocalEGA-tester/pull/28 is merged ?

**Pull request merged**
